### ISSUE TITLE
Failed to verify module.prop

### ISSUE THREAD

**Issue by Vinayak2101** [tryigit/PlayIntegrityFix#10]
I am getting error 

```
failed to verify module.prop
The zip may be corrupted. Please Try again
```

I am using samsung f23 5g. tried in stock kernel as well as custom kernel
Same error in Xiaomi Poco m6 pro also. It was working fine before. but now it isnt

tried in magisk as well as ksu. got the same error

Thanks

**Comment by tryigit** [comment]
Incorrect zip installation, fixed.
