### ISSUE TITLE
First reboot after install won't start phone

### ISSUE THREAD

**Issue by ElDavoo** [tryigit/PlayIntegrityFix#12]
Hi,
It's not really a problem for me, but after installing or updating this module, the first reboot will not start the phone, that will be stuck on logo without doing anything and without ADB (so i cannot grab logs.)
After forcingly rebooting with power button, everything seems to work fine (I mean, i don't pass integrity, but phone works)

**Comment by tryigit** [comment]
If you have met the Readme.md requirements, tell us your Android version, os and which module you are using

Close issue if you haven't read it.

**Comment by ElDavoo** [comment]
LOS 20 and PIFS v1.0.5 (also v1.0.4 was doing the same thing)

**Comment by tryigit** [comment]
Only Official roms.

Take a good look at the purpose of this fork
