### ISSUE TITLE
China? :D

### ISSUE THREAD

**Issue by Shidapu** [tryigit/PlayIntegrityFix#14]
Why so many mentions of China everywhere?

This module works great and gives me strong integrity and bypass every Integrity check.
Official Samsung Fold 3 firmware, no xiaomi.

**Comment by tryigit** [comment]
Read the Github readme file.
For other users it makes more sense to use the original version 1.1, only the random Keybox function and the log functions of this module make sense for other roms.

**Comment by Shidapu** [comment]
> Read the Github readme file. For other users it makes more sense to use the original version 1.1, only the random Keybox function and the log functions of this module make sense for other roms.

I cant find the 1.1 you mention in your release section? With the original author Tricky Store it wont pass strong integrity.

**Comment by tryigit** [comment]
> > Read the Github readme file. For other users it makes more sense to use the original version 1.1, only the random Keybox function and the log functions of this module make sense for other roms.
> 
> I cant find the 1.1 you mention in your release section? With the original author Tricky Store it wont pass strong integrity.

Just use a random Keybox.
Random from within the repo or module

That's probably the only reason
