### ISSUE TITLE
Search bot suggestion

### ISSUE THREAD

**Issue by re7gog** [tryigit/PlayIntegrityFix#16]
If we have problem with indexing search bot, let's abuse https://github.com/robots.txt, and place keybox files in tarball or zipball directory

**Comment by re7gog** [comment]
Btw, thanks for key, it worked❤️❤️❤️

**Comment by tryigit** [comment]
> If we have problem with indexing search bot, let's abuse https://github.com/robots.txt, and place keybox files in tarball or zipball directory

It would be better if you send a pull request for this. To match the skull subdirectory.

I'm lazy and it's a good idea thanks.

**Comment by abdulros1d** [comment]
Ok siap
