### ISSUE TITLE
All remaining keyboxes have been revoked (I think?)

### ISSUE THREAD

**Issue by Thisisauser6443** [tryigit/PlayIntegrityFix#20]
![Damn it](https://github.com/user-attachments/assets/28a9a7ba-cedb-4af2-ba48-f01194dbfc85)

**Comment by Numaphor** [comment]
can confirm this.

**Comment by Thisisauser6443** [comment]
It truly is the end of an era :/

**Comment by Numaphor** [comment]
There are still unrevoked keyboxes, people just hold them privately, as they get banned as soon as they share them.
If you search telegram for long enough you will find them

BUT PLEASE KEEP IN MIND, DO YOU REALLYYYY NEED STRONG??
maybe you only need STRONG for 1 or 2 apps, in this case it may just be easier to switch out those apps

**Comment by Thisisauser6443** [comment]
@Numaphor, I'm familiar with most apps just requiring a spoofed locked bootloader or passing device integrity. The **ONLY** reason I'd want a KB is simply so I can get the built-in VPN for my Pixel 8 working. 

Other than that, it's just the whole "2 tIcKs bAd, 3 TiCkS gOoD" thing, but as we all know, that's just a nice-to-have instead of an essential aspect
