### ISSUE TITLE
Can not install on Android 10

### ISSUE THREAD

**Issue by Robin-zero** [tryigit/PlayIntegrityFix#5]
![Screenshot_2024-01-20-01-24-02-363_klljov.k.jpg](https://github.com/tryigit/PlayIntegrityFix/assets/22169252/6f5994b7-e2c6-4e26-bf2e-d4f17b61858d)

**Comment by tryigit** [comment]
Module developed for **HyperOS based China roms.** I recommend using the chiteroman original module if you don't have it.

However, there is an easy way to use the module.

Open the Zip file and edit this file
`customize.sh`

```
# Error on < Android 10.
if [ "$API" -lt 29 ]; then
    ui_print " "
    ui_print "- ❗ You can't use this module on Android < 10.0"
    abort " "
fi
```

If you edit it this way, you can install the module.

**Comment by Robin-zero** [comment]
Thanks, it worked 🥰

**Comment by kapoorrohit19-pixel** [comment]
Also getting error: sdk required 29.
current sdk 28.
