### ISSUE TITLE
Failed to pass play integrity and cts check after reset lock prop

### ISSUE THREAD

**Issue by scruel** [tryigit/PlayIntegrityFix#7]
Xiaomi cas, android 13
After executing `resetprop ro.secureboot.lockstate locked`, device will back to the failed passing state.
ZygsikMod-v4-0.9.3-211-6449b1f, apatch 10772

After factory reset,this module stops working anymore...

**Comment by tryigit** [comment]
Do you use shamiko?
It seems more like an apatch issue, resetprop is based on Magisk

You can try to edit (resetprop) the service.sh and post-fs-data.sh  file according to your needs.

**Comment by scruel** [comment]
No, I didn't use shamiko, Apatch has bad support for it.
I failed to reproduce this again, so I will close this issue, and I will reopen it with log file attached if I can reproduce this again.
BTW, it seems either the original PIF or your fork won't be able to set `ro.secureboot.lockstate` correctly (or maybe reset again) after system booted.
