### ISSUE TITLE
相比原版会导致zygiskd startup error

### ISSUE THREAD

**Issue by lisiupython** [tryigit/PlayIntegrityFix#8]
小米 android13，原版启动正常，本项目的版本会导致zygisk启动失败，日志显示：
read failed with 104: Connection reset by peer
zygiskd startup error

会导致一些隐藏root失效，比如农业银行，或者某些程序的hook失效

**Comment by tryigit** [comment]
This is not a bug/error but a feature of the module. I can't do anything about 32bit banking applications.

https://github.com/tryigit/PlayIntegrityFix?tab=readme-ov-file#features

_Permanently removing 32bit support for Magisk and modules_
